-- MySQL Script generated by MySQL Workbench
-- Thursday 21 June 2018 05:38:56 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema IRCTC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema IRCTC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IRCTC` DEFAULT CHARACTER SET utf8 ;
USE `IRCTC` ;

-- -----------------------------------------------------
-- Table `IRCTC`.`train`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IRCTC`.`train` (
  `train_id` INT NOT NULL,
  `train_name` VARCHAR(45) NOT NULL,
  `source` VARCHAR(45) NOT NULL,
  `destination` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`train_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IRCTC`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IRCTC`.`ticket` (
  `ticket_id` INT NOT NULL,
  `ticket_price` INT NOT NULL,
  `from` VARCHAR(45) NOT NULL,
  `to` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ticket_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IRCTC`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IRCTC`.`customer` (
  `customer_id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `contact_no` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IRCTC`.`reserved_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IRCTC`.`reserved_ticket` (
  `ticket_id` INT NOT NULL,
  `customer_id` INT NULL,
  `train_id` INT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  PRIMARY KEY (`ticket_id`),
  INDEX `fk_reserved_ticket_2_idx` (`customer_id` ASC),
  INDEX `fk_reserved_ticket_3_idx` (`train_id` ASC),
  CONSTRAINT `fk_reserved_ticket_1`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `IRCTC`.`ticket` (`ticket_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserved_ticket_2`
    FOREIGN KEY (`customer_id`)
    REFERENCES `IRCTC`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserved_ticket_3`
    FOREIGN KEY (`train_id`)
    REFERENCES `IRCTC`.`train` (`train_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IRCTC`.`unreserved_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IRCTC`.`unreserved_ticket` (
  `ticket_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`ticket_id`),
  INDEX `fk_unreserved_ticket_2_idx` (`customer_id` ASC),
  CONSTRAINT `fk_unreserved_ticket_1`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `IRCTC`.`ticket` (`ticket_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_unreserved_ticket_2`
    FOREIGN KEY (`customer_id`)
    REFERENCES `IRCTC`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
